base_url: https://ion.inapi.cl
url_busca_marca: /Marca/BuscarMarca.aspx/FindMarcas
url_busca_por_solicitud: /Marca/BuscarMarca.aspx/FindMarcaByNumeroSolicitud
proxy: False
proxy_ip_port:
output_file_name: salida
output_dir: C:/Users/LNKIZ/Desktop/Test python/proyecto/request_inapi/files/
registers_list_file_name: register_number_list.txt
register_list_dir: C:/Users/LNKIZ/Desktop/Test python/proyecto/request_inapi/files/
numero_hilos: 5